### ISSUE TITLE
REPL is broken on Linux

### ISSUE THREAD

**Issue by thoughtpolice** [thoughtpolice/cryptol-mode#1]
On my Ubuntu 12.10 machine, `cryptol-mode` is broken due to (I believe) incorrectly detected `$TERM` settings. When you launch the terminal, any keystrokes will cause `cryptol` to immediately exit. This is obviously a very bad bug.

Launching the REPL on my OS X machine Emacs correctly seems to set `$TERM` to `dumb`, and the REPL works just fine for playing around. It also does this for Linux, but it seems as if `terminfo` (which the `cryptol` executable is linked to) always reports that it cannot find the `dumb` mode despite having all the prerequisite packages installed.

I'll try to provide more details shortly but I realized I hadn't filed this.

**Comment by david-christiansen** [comment]
This is working fine for me on Fedora 27, Cryptol 2.5.0, and GNU Emacs 25.3.1.

**Comment by thoughtpolice** [comment]
Yes, this was an ancient issue with Cryptol 1, which we have no real need to support anymore. (I should prune out these bugs for v1 since they're not very relevant anymore...)
